"""What more than one backend needs, in one place."""

import logging
import re
from typing import Dict, List, Optional
from functools import lru_cache

logger = logging.getLogger(__name__)

# Operators that read a phrase list from a file next to the rules. No backend
# that converts a rule to a single pattern can carry a file with it.
UNSUPPORTED_FILE_OPERATORS = ("@pmFromFile",)


def provenance_header(crs_ref: str, title: str) -> str:
    """
    The attribution block at the top of every generated file.

    Records that the output is a derived/converted work of the OWASP Core Rule
    Set (Apache-2.0). See THIRD_PARTY_NOTICES.md.

    Args:
        crs_ref: The upstream tag the rules were read from.
        title: How the target is named, such as "Nginx".
    """
    return (
        f"# Generated by fabriziosalmi/patterns from OWASP CoreRuleSet ({crs_ref}), "
        f"Apache-2.0; converted to {title}.\n"
        "# Source rules: https://github.com/coreruleset/coreruleset\n"
        "# Derived/converted work redistributed under Apache-2.0. "
        "See THIRD_PARTY_NOTICES.md.\n"
        "#\n"
    )


_TOML_ESCAPES = {"\\": "\\\\", '"': '\\"', "\b": "\\b", "\t": "\\t", "\n": "\\n",
                 "\f": "\\f", "\r": "\\r"}


def toml_string(value: str) -> str:
    """
    Writes a string as TOML, so that a parser reads back exactly `value`.

    A regular expression is full of backslashes, and in a TOML basic string
    (`"..."`) a backslash starts an escape: `"^\\$"` is not valid TOML, and Traefik
    refuses the file before it reaches a middleware (#69). A literal string
    (`'...'`) takes every character as it is, so that is used when it can be: it
    cannot hold a single quote or a control character, and then the string is
    written as a basic one with those escaped.
    """
    if "'" not in value and not any(ord(c) < 0x20 or ord(c) == 0x7F for c in value):
        return f"'{value}'"
    out = []
    for c in value:
        if c in _TOML_ESCAPES:
            out.append(_TOML_ESCAPES[c])
        elif ord(c) < 0x20 or ord(c) == 0x7F:
            out.append("\\u%04X" % ord(c))
        else:
            out.append(c)
    return '"' + "".join(out) + '"'


def modsecurity_quote(value: str) -> str:
    """
    Writes a string between the double quotes of a ModSecurity directive, so that what
    ModSecurity reads is exactly `value`.

    Apache reads a quoted argument before ModSecurity sees it, and takes `\\\\` for one
    backslash and `\\"` for a quote. A regular expression that means a literal backslash
    has to arrive with it doubled, or it is another expression: this is what
    `re.escape` was doing the wrong way round (#55).
    """
    return value.replace("\\", "\\\\").replace('"', '\\"')


def modsecurity_unquote(text: str) -> str:
    """
    What ModSecurity reads from the text between the quotes of a directive: the
    inverse of `modsecurity_quote`. CRS writes its arguments this way, and the IR keeps
    them as written, so this is the regular expression the engine compiles.
    """
    return re.sub(r'\\(["\\])', r"\1", text)


_YAML_ESCAPES = {"\\": "\\\\", '"': '\\"', "\t": "\\t", "\n": "\\n", "\r": "\\r", "\x85": "\\N",
                 "\u2028": "\\L", "\u2029": "\\P"}


def yaml_string(value: str) -> str:
    """
    Writes a string as a YAML scalar, so that a parser reads back exactly `value`.

    A single-quoted scalar takes every character as it is and only a quote has to be
    doubled, which is what a regular expression full of backslashes needs: in a
    double-quoted one `\\d` is an error. A single-quoted scalar cannot hold a control
    character or a line break, and then the string is written double-quoted with those
    escaped.
    """
    if all(c == "\t" or " " <= c <= "~" or c >= "\xa0" and c not in "\u2028\u2029" for c in value):
        return "'" + value.replace("'", "''") + "'"
    out = []
    for c in value:
        if c in _YAML_ESCAPES:
            out.append(_YAML_ESCAPES[c])
        elif ord(c) < 0x20 or 0x7F <= ord(c) < 0xA0:
            out.append("\\x%02X" % ord(c))
        else:
            out.append(c)
    return '"' + "".join(out) + '"'


def ascii_lower(value: str) -> str:
    """What `t:lowercase` in ModSecurity and `lower` in HAProxy do: ASCII only, as C's tolower does."""
    return "".join(c.lower() if c < "\x80" else c for c in value)


def haproxy_pattern(expression: str) -> str:
    """
    One regular expression as a line of an HAProxy pattern file.

    HAProxy reads the file a line at a time, takes each line for a pattern as it stands (no
    quoting, so `#` in the middle and any length are fine) and drops what it would drop of a
    line: blank space at either end, and a line that starts with `#`. A pattern that begins
    or ends with a space, or begins with `#`, would become another pattern, so that
    character is written with the backslash PCRE gives it to mean itself.
    """
    if expression[:1] in (" ", "\t", "#"):
        expression = "\\" + expression
    if expression[-1:] in (" ", "\t"):
        slashes = len(expression) - len(expression[:-1].rstrip("\\"))  - 1
        if slashes % 2 == 0:  # an even number of backslashes before it: it is not escaped yet
            expression = expression[:-1] + "\\" + expression[-1]
    return expression


def without_handled_syntax(argument: str) -> str:
    """
    What a regular expression is once the syntax a backend handles another way
    is taken out: `(?i)`, which it replaces with a case-insensitive match, and
    `(?:`, which it writes as `(`. Neither changes what the expression matches,
    so a backend that writes anything else has rewritten it.
    """
    return argument.replace("(?i)", "").replace("(?:", "(").strip()


@lru_cache(maxsize=256)
def validate_regex(pattern: str) -> bool:
    """Reports whether Python's `re` compiles the pattern."""
    try:
        re.compile(pattern)
        return True
    except re.error as e:
        logger.warning(f"Invalid regex: {pattern} - {e}")
        return False


def phrases_of(operator: dict, data_files: Dict[str, List[str]]) -> Optional[List[str]]:
    """
    The phrases an `@pm` or `@pmFromFile` operator matches, or None if it is neither.

    `@pm` takes its phrases from its argument, split on blank space. `@pmFromFile` takes
    them from the file the argument names, which the IR carries (`data_files`): None when it
    does not, because a rule written without its phrases would not say what it is for.
    """
    if operator["negated"] or operator["name"] not in ("pm", "pmFromFile"):
        return None
    if operator["name"] == "pm":
        return operator["argument"].split()
    return data_files.get(operator["argument"].strip())


def operator_of(rule: dict) -> dict:
    """
    The operator of a rule as the IR spells it: name, negated, argument.

    A rule from a document that predates the IR has none, and gets it read out of
    `pattern` (`@rx foo`, `!@pm a b`, or a bare expression, which is `@rx`).
    """
    operator = rule.get("operator")
    if operator is not None:
        return operator
    text = rule.get("pattern", "").strip()
    negated = text.startswith("!")
    body = text[1:] if negated else text
    if body.startswith("@"):
        name, _, argument = body[1:].partition(" ")
        return {"name": name, "negated": negated, "argument": argument.strip()}
    return {"name": "rx", "negated": negated, "argument": body}
