"""What more than one backend needs, in one place."""

import logging
import re
from functools import lru_cache

logger = logging.getLogger(__name__)

# Operators that read a phrase list from a file next to the rules. No backend
# that converts a rule to a single pattern can carry a file with it.
UNSUPPORTED_FILE_OPERATORS = ("@pmFromFile",)


def provenance_header(crs_ref: str, title: str) -> str:
    """
    The attribution block at the top of every generated file.

    Records that the output is a derived/converted work of the OWASP Core Rule
    Set (Apache-2.0). See THIRD_PARTY_NOTICES.md.

    Args:
        crs_ref: The upstream tag the rules were read from.
        title: How the target is named, such as "Nginx".
    """
    return (
        f"# Generated by fabriziosalmi/patterns from OWASP CoreRuleSet ({crs_ref}), "
        f"Apache-2.0; converted to {title}.\n"
        "# Source rules: https://github.com/coreruleset/coreruleset\n"
        "# Derived/converted work redistributed under Apache-2.0. "
        "See THIRD_PARTY_NOTICES.md.\n"
        "#\n"
    )


@lru_cache(maxsize=256)
def validate_regex(pattern: str) -> bool:
    """Reports whether Python's `re` compiles the pattern."""
    try:
        re.compile(pattern)
        return True
    except re.error as e:
        logger.warning(f"Invalid regex: {pattern} - {e}")
        return False
